---
config: # The global variables are defined here
    path: ['/Users/pradeech/TestOpenstackHA/']
    repeat: 1
    delay: 30   # repeats after every 30seconds.

disruptors:
    service:
        hh24-tb1:
            ip: 172.22.191.136
            username: root
            password: cisco123
            services: [console, l3]
monitors:
    # plugin name
    nagiosMonitor: 
        nagios: 
            ip: 172.22.191.244
runners:
    rally:
        glance_test:
            scenario_name: glance
            scenario_file: glance.json
executors:
    # mode is the built in command
    -
        mode: parallel
        repeat: 1
        # execute: [glance_test]
        start_disruption: [hh24-tb1]
        start: [nagios]
    -
...
