disruptors:
  disruptor:
    control-1:
      ip: 172.22.191.136
      password: cisco123
      role: controller
      user: root
    network-1:
      ip: 172.22.191.137
      password: cisco123
      role: network
      user: root
