disruptors:
    node_disruptor:
       # Controller where all control plane are combined in one node (common case)
       allinone_ controller:
           role : controller

       # All in one controller with seperate network node(common case)
       allinone_controller_1:
           role: controller_1

       # Below options define where each service is running on seperate node
       # If this does not fit use custom controller option
       rabbitmq_controller:
           role : rabbit
       galera_controller:
           role:  mysql
       haproxy_controller:
           role:  haproxy
       keystone_controller:
           role:  keystone
       glance_controller:
           role:  glance
       network_controller:
           role : network
       neutron_controller:
           role : neutron_api
       nova_controller:
           role: nova
       cinder_controller:
           role: cinder
       horizon_controller:
           role: horizon
       compute_node:
           role: compute

       # Where specific services are running in a controller
       custom_controller:
           role: nova, cinder
 
    container_disruptor:
       keystone_container:
           container_name: keystone_v1
           role: controller

    process_disruptor:
       nova_api:
           process_name : openstack-nova-api.service
           role : controller
           type : graceful
       neutron_api:
           process_name : neutron-server.service
           role: controller
           type: graceful
       rabbitmq_api:
           process_name: rabbitmq-server
           role: controller
           type: graceful
       glance_api:
           process_name: openstack-glance-api.service
           role: controller
           type: graceful
       glance_registry:
           process_name: openstack-glance-registry
           role: controller
           type: graceful
       nova_novnc:
           process_name: openstack-nova-novncproxy
           role : controller
           type: graceful
       nova_conductor:
           process_name : openstack-nova-conductor
           role: controller
           type: graceful
       nova_scheduler:
           process_name: openstack-nova-scheduler.service
           role : controller
           type: graceful
       dhcp_agent:
           process_name: neutron-dhcp-agent
           role : controller
           type: graceful
       ovs_agent:
           process_name: neutron-openvswitch-agent
           role : controller
           type: graceful
       neutron_metadata:
           process_name: neutron-metadata-agent
           role: controller
           type: graceful
       neutron_l3:
           process_name: neutron-l3-agent
           role : controller
           type: graceful
       nova_compute:
           process_name : openstack-nova-compute
           role : compute
           type: graceful
