disruptors:
    baremetal:
        node_1:
            ip: 172.31.231.181
            username: root
            password: cisco123
            notification: [key_mon, rally_run]
        node_2:
            ip: 80.1.1.1
            username: root
            password: cisco123
    network:
        node_3:
            ip: 172.29.68.150
            username: root
            password: cisco123
            notification: [key_mon, rally_run]
        node_4:
            ip: 80.1.1.1
            username: root
            password: cisco123


