executors:
    # mode and repeat are mandatory for each block
    # mode =  parallel|sequence -> execution mode
    # repeat = number of times to repeat the block
    # ha_interval = interval time between disruptions
    # sync = true|false -> enable synchronization within the block
    -
        # infra parameters
        mode: parallel
        repeat: 1
        sync: true
        ha_interval: 10
        # disruption scenario
        #node_disruption : [glance_controller, neutron_controller]
        execute: [rally_sanity]
        start: [openstack_api]
        process_disruption: [nova_api, neutron_api, glance_api]
    -
