executors:
    # mode and repeat are mandatory for each block
    # mode =  parallel|sequence -> execution mode
    # repeat = number of times to repeat the block
    # ha_interval = interval time between disruptions
    # sync = true|false -> enable synchronization within the block
    -
        # infra parameters
        mode: parallel
        repeat: 1
        sync: true
        ha_interval: 45 

        # disruption scenario
        node_disruption : [compute_node]
        execute: [boot_test]
        start: [openstack_api, ansible]
        #process_disruption: [nova_scheduler]
    -
