executors:
    # mode and repeat are mandatory for each block
    -
        # Create Disruptions in the cloud
        mode: parallel
        repeat: 1
        #node_disruption : [control-1]
        #execute: [rally_sanity]
        #start: [openstack_api]
        start: [nagioscfg,nagios]
    -
        # Run your sanity scripts
        mode: parallel
        repeat: 1
        execute: [rally_sanity]
    -
