monitors:
    # plugin name
    keystone:
        # list
        keystone_service:
            ip:
            user:
            password:
        keystone_service1:
            ip:
            user:
            password:
    neutron:
        neutron_service:
            ip:
            user:
            password:
    processes:
        libvirt:
            ip:
            pid:
    nagiosmonitor:
        nagios:
            ip: 12.2
            a:
            b:
    healthapi:
        openstack_api:
            openrc_file:
            password:

