# Define your openstack VM nodes with ip and password info
control-1:
    ip: 10.30.117.233
    user: root
    password: ''
    role: controller
compute-1:
    ip: 10.30.117.230
    user : root
    password: ''
    role: compute
compute-2:
    ip: 10.30.117.231
    user: root
    password: ''
    role: compute
control-2:
    ip: 10.30.117.229
    user: root
    password: ''
    role: controller
control-3:
    ip: 10.30.117.232
    user: root
    password: ''
    role: controller
