control-1:
    ip: 172.22.191.154
    user: root
    password: cisco123
    role: controller
compute-1:
    ip: 172.22.191.154
    user: root
    password: cisco123
    role: compute
compute-2:
    ip: 172.22.191.154
    user: root
    password: cisco123
    role: compute
