control-1:
    ip: 172.29.87.40
    user: root
    password: cisco123
    role: controller
compute-1:
    ip: 172.31.231.17
    user: root
    password: cisco123
    role: compute
compute-2:
    ip: 172.31.231.25
    user: root
    password: cisco123
    role: compute
