runners:
    rally:
        rally_sanity:
            scenario_name: sanity
            rally_path: /usr/local/bin/rally
            scenario_file: /Users/pradeech/infraRally/rally/samples/tasks/scenarios/nova/boot.json
