runners:
   # Sample runner file
   # <runner_name>: (Name of backend plugin class for runner in runners/plugins)
   #    <runner_ref>: (Logical name for runner test specified in executor.yaml)
   #        <input_parameters> : (Input parameters passed to the runner class)
    rally:
        # Rally boot test
        boot_test:
            scenario_name: boot 
            rally_path:  /usr/bin/rally 
            scenario_file: /root/rally/rally/boot.json
        keystone_test:
            scenario_name: keystone
            rally_path: /usr/bin/rally
            scenario_file : /root/rally/rally/create_tenant_with_users.json
 
