runners:
   # Sample runner file
   # <runner_name>: (Name of backend plugin class for runner in runners/plugins)
   #    <runner_ref>: (Logical name for runner test specified in executor.yaml)
   #        <input_parameters> : (Input parameters passed to the runner class)
    rally:
        # Rally boot test
        boot_test:
            scenario_name: boot 
            rally_path:  /home/ubuntu/rally/bin/rally 
            scenario_file: /home/ubuntu/cisco-rally/rally/boot.json
        keystone_test:
            scenario_name: keystone
            rally_path: /home/ubuntu/rally/bin/rally
            scenario_file : /home/ubuntu/cisco-rally/rally/create-tenant-with-users.json
        cinder_test:
            scenario_name: cinder
            rally_path: /home/ubuntu/rally/bin/rally
            scenario_file : /root/rally/rally/create-and-delete-volume.json
        neutron_test:
            scenario_name: neutron
            rally_path: /home/ubuntu/rally/bin/rally
            scenario_file : /root/rally/rally/create_and_list_ports.json 
