---
config: # The global variables are defined here
    path: ['/Users/pradeech/HA1/Cloud_HA_Testframework']
    repeat: 1
    delay: 30   # repeats after every 30seconds.

disruptors:
    baremetal:
        node_1:
            ip: 172.29.68.150
            username: root
            password: cisco123
            notification: [key_mon, rally_run]
        node_2:
            ip: 80.1.1.1
            username: root
            password: cisco123
    network:
        node_3:
            ip: 172.29.68.150
            username: root
            password: cisco123
            notification: [key_mon, rally_run]
        node_4:
            ip: 80.1.1.1
            username: root
            password: cisco123
    process:
        nova_api:
            ip:
            list:[]
        network_server:
            ip:
            list: []
# top HA directory
monitors:
    # plugin name
    keystone:
        # list
        keystone_service:
            ip:
            user:
            password:
        keystone_service1:
            ip:
            user:
            password:
    neutron:
        neutron_service:
            ip:
            user:
            password:
    processes:
        libvirt:
            ip:
            pid:

runners:
    rally:
        keystone_authentication:
            scenario_name: keystone
            scenario_file: keystone.json
        #scenario_2:
        #    scenario_name: Volume
    tempest:
        testcase_1:
            api:
            neutron:

executors:
    # mode is the built in command
    -
        mode: parallel
        repeat: 3
        execute: [keystone_authentication]
        start_disruption: [node_1, nova_api]
        #publishers: [keystone_authentication]
        #subscribers: [keystone_service, neutron_service]
    -
        report: [keystone_authentication]
   # -
   #     report: [keystone_authentication]
...
